spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pos
    username: root
    password: 1212
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true